# Generated by Django 4.1.2 on 2022-11-18 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_torneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='fecha_tor_emp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 13, 31, 20, 900741), verbose_name='Fecha de inicio'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='fecha_tor_fin',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 13, 31, 20, 900741), verbose_name='Fecha de finiquito'),
        ),
    ]
