# Generated by Django 4.1.2 on 2023-02-03 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_articulo_alter_noticia_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='img',
            field=models.ImageField(default=1, upload_to='static/media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha_venta',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 12, 22, 14, 978681), verbose_name='Fecha de venta'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fecha_tor_emp',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 12, 22, 14, 978681), verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fecha_tor_fin',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 12, 22, 14, 978681), verbose_name='Fecha de finiquito'),
        ),
    ]
