# Generated by Django 4.1.2 on 2023-02-23 12:55

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio', '0013_alter_articulo_fecha_venta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AddField(
            model_name='torneo',
            name='concursantes',
            field=models.ManyToManyField(blank=True, null=True, related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha_venta',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 13, 55, 2, 621903), verbose_name='Fecha de venta'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fecha_tor_emp',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 13, 55, 2, 620908), verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fecha_tor_fin',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 13, 55, 2, 620908), verbose_name='Fecha de finiquito'),
        ),
    ]
