# Generated by Django 4.1.2 on 2023-02-24 11:32

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio', '0014_delete_cliente_torneo_concursantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha_venta',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 12, 32, 39, 468516), verbose_name='Fecha de venta'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='concursantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fecha_tor_emp',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 12, 32, 39, 468516), verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fecha_tor_fin',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 12, 32, 39, 468516), verbose_name='Fecha de finiquito'),
        ),
    ]
