# Generated by Django 4.1.2 on 2022-11-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='titular',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
