# Generated by Django 4.1.2 on 2022-11-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_alter_noticia_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(verbose_name='Noticia a '),
        ),
    ]
