# Generated by Django 4.1.2 on 2023-03-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0016_alter_articulo_fecha_venta_alter_torneo_concursantes_and_more'),
        ('sitio', '0018_alter_articulo_fecha_venta_alter_cliente_contrasenha_and_more'),
    ]

    operations = [
    ]
